name: Deploy to PROD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
  runs-on: self-hosted

  steps:
  - name: Revisar cambios en la main
    uses: actions/checkout@v4
    with:
    clean: false

  - name: Actualizar forzosamente a la main
    run: |
      # Asegurate que la ruta sea la correcta en tu PROD
      cd /var/www/Bonafide 
      git fetch --all
      git reset --hard origin/main # Fuerza a que sea idéntico a main

  - name: Actualizar librerías de npm
    run: |
      cd /var/www/Bonafide/API
      npm install --production

  - name: Reiniciar Node.js
    run: |
      # Asumo que usas PM2 como vimos antes
      pm2 restart bonafide-api || pm2 start index.js --name "bonafide-api"
      pm2 save